### ISSUE TITLE
Potential UniFi caching issue

### ISSUE THREAD

**Issue by amccarthy-figma** [0xdabbad00/security_incidents_from_caching#1]
https://www.reddit.com/r/Ubiquiti/comments/18hgpw1/security_problem/?share_id=yUmL6IOwgoKmgd3idJqk9&utm_content=2&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1

**Comment by 0xdabbad00** [comment]
Thank you @amccarthy-figma ! I've added it.
